[package]
name = "nodetool-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inner = "0.1.1"
thiserror = "1.0.30"

[dev-dependencies]
anyhow = "1.0.53"
